GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "This is a test to see if post works",
    "important": true
}

###

GET http://localhost:3001/api/notes
